name: CI
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Print env
      run: env

    - name: Read event json
      run: cat $GITHUB_EVENT_PATH

    - name: Build
      run: make -f docker.Makefile

    - name: E2E
      run: make -f docker.Makefile test-e2e
