name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: DOCKER_BUILDKIT=1 make -f docker.Makefile build

    - name: E2E
      run: DOCKER_BUILDKIT=1 make -f docker.Makefile test-e2e
